### ISSUE TITLE
[1.16.5 Enhancement] Dynamically Support Modded Loot Injections

### ISSUE THREAD

**Issue by Dradon7** [Uraneptus/SnowPig-forge-1.16#1]
Repurposed Structures (by telepathicgrunt) has some really interesting code. Its structures copy vanilla ones, so it dynamically supports loot injection into the tables. Basically, the RP birch mineshaft will have any loot injections of other mods that inject stuff into the vanilla mineshaft.
Thats relevent because you could so the same thing for the snow pig loot table. This would automatically support stuff like Quark's tallow and Farmer's delight's ham, which is injected into the vanilla pig loottable. Here's the github: [https://github.com/TelepathicGrunt/RepurposedStructures](https://github.com/TelepathicGrunt/RepurposedStructures). Would something like this be possible?

**Comment by Uraneptus** [comment]
Thanks for the suggestion!
Will be added
