### ISSUE TITLE
[SUGGESTION]Make a config that allow to change spawn biomes

### ISSUE THREAD

**Issue by S1mpleM0use** [Uraneptus/SnowPig-forge-1.16#11]
That's pretty much it :)

**Comment by Uraneptus** [comment]
There is no need for a config in 1.19+, since you can just edit this tag [(https://github.com/Uraneptus/SnowPig-forge/blob/1.19/src/main/resources/data/snowpig/tags/worldgen/biome/snow_pig_spawn_in.json)](url) to change the spawn biome
