### ISSUE TITLE
[1.21-Neo] Crash running around world past NeoForge version .74 and above.

### ISSUE THREAD

**Issue by Gbergz** [Uraneptus/SnowPig-forge-1.16#15]
### Minecraft version information

1.21

### Mod loader information

NeoForge

### Mod loader version information

21.0.78

### Mod version information

8.0.0

### Reproduction Steps

Go into a world
run around, or open creative tab.
crash.

### Crash Report and latest.log

https://gist.githubusercontent.com/Gbergz/fdd204927d081cd54c64cdd15610d9e9/raw/9a8e6a4321fb3c2f550d3cf8dd54215619f955a8/gistfile1.txt

### Additional information

Basically it.

**Comment by Uraneptus** [comment]
This is probably caused by a breaking change in Neo 21.0.66. Snowpig 8.0.0 is running on 21.0.0
I will update snowpig to work with the newer version, this should probably fix it ^^

**Comment by Uraneptus** [comment]
I uploaded a fix. Lemme know if the new update still causes crashes.
