### ISSUE TITLE
Couldn't parse loot table

### ISSUE THREAD

**Issue by ghost** [Uraneptus/SnowPig-forge-1.16#4]
Using mc 1.18.1
Forge 39.0.0
snow pig 1.18.1-1.0.0

This appears in the server console at startup and the server latest.log

[snowpig.txt](https://github.com/Uraneptus/SnowPig-forge/files/7721079/snowpig.txt)

**Comment by Uraneptus** [comment]
Does it crash?

**Comment by ghost** [comment]
> Does it crash?

It does not crash. But its spamming almost 100 lines of that error. Idk what a failed loot table affects

**Comment by Uraneptus** [comment]
Yeah that's quite a lot of spam. Gonna fix that!

**Comment by Uraneptus** [comment]
https://www.curseforge.com/minecraft/mc-mods/snow-pig/files/3567747
Could you try this version and tell me if it's fixed?
