### ISSUE TITLE
Snow Pig has failed to load correctly

### ISSUE THREAD

**Issue by KondiU** [Uraneptus/SnowPig-forge-1.16#5]
When using Snow Pig 2.4.1 on 1.16.5, the game crashes with the following log:

[crash-2021-12-28_19.35.04-fml.txt](https://github.com/Uraneptus/SnowPig-forge/files/7785977/crash-2021-12-28_19.35.04-fml.txt)

This issue is not happening on older versions of this mod

**Comment by Uraneptus** [comment]
You're using forge 36.2.4. This SnowPig version only works for forge versions above 36.2.17 tho.
Forgot to state that in the changelog for this update, my bad!
